FROM ubuntu:18.04

RUN apt-get update -y && apt-get -y install tesseract-ocr tesseract-ocr-tam python3 python3-pip

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 3001

CMD ["python3", "meme-text-service.py"]
